version: 2

sources:
  - name: src_ads
    tables:
      - name: src_ads_creative_facebook_all_data
      - name: src_ads_bing_all_data
      - name: src_ads_tiktok_ads_all_data
      - name: src_promoted_tweets_twitter_all_data
